// Required by Google Play Store and Apple App Store.
// This page must be publicly accessible — no auth required.

import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="sticky top-0 z-10 bg-background border-b">
        <div className="flex items-center gap-3 p-4 max-w-2xl mx-auto">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <h1 className="font-semibold">Terms of Service</h1>
        </div>
      </div>

      <div className="max-w-2xl mx-auto p-6 space-y-6 text-sm leading-relaxed">

        <div>
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        </div>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">1. Acceptance of Terms</h2>
          <p>
            By downloading, installing, or using the QuickChef application ("App"), you agree
            to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms,
            do not use the App.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">2. Description of Service</h2>
          <p>
            QuickChef is an AI-powered cooking assistant that generates personalized recipe
            suggestions based on your available ingredients, dietary preferences, and goals.
            The App provides recipe generation, pantry management, and recipe saving features.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">3. User Accounts</h2>
          <p>You must create an account to use QuickChef. You are responsible for:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activity that occurs under your account</li>
            <li>Providing accurate and complete registration information</li>
            <li>Notifying us immediately of any unauthorized account access</li>
          </ul>
          <p>You must be at least 13 years old to create an account.</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">4. Free Tier and Usage Limits</h2>
          <p>
            Free accounts are limited to 2 AI recipe generations per day. This limit resets
            at midnight. We reserve the right to modify usage limits at any time with reasonable
            notice. Attempting to circumvent usage limits by creating multiple accounts is
            a violation of these Terms.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">5. AI-Generated Content</h2>
          <p>
            Recipes generated by QuickChef are produced by artificial intelligence and are
            provided for informational and entertainment purposes only. You acknowledge that:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>AI-generated recipes may contain errors or inaccuracies</li>
            <li>Nutritional information is estimated and not guaranteed to be accurate</li>
            <li>You should exercise judgment regarding food safety and cooking times</li>
            <li>QuickChef is not a substitute for professional dietary or medical advice</li>
            <li>If you have food allergies, always verify ingredients carefully</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">6. Prohibited Conduct</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the App for any unlawful purpose</li>
            <li>Attempt to reverse engineer or modify the App</li>
            <li>Use automated tools to access the App or its API</li>
            <li>Create multiple accounts to circumvent usage limits</li>
            <li>Interfere with the App's servers or infrastructure</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">7. Intellectual Property</h2>
          <p>
            The QuickChef application, including its design, code, and branding, is owned by
            QuickChef and protected by intellectual property laws. AI-generated recipes produced
            through your use of the App may be saved and used for your personal, non-commercial
            cooking purposes.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">8. Disclaimer of Warranties</h2>
          <p>
            QuickChef is provided "as is" without warranties of any kind, either express or
            implied. We do not warrant that the App will be uninterrupted, error-free, or
            free of harmful components. AI-generated content is not guaranteed to be accurate,
            complete, or suitable for any particular purpose.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, QuickChef shall not be liable for any
            indirect, incidental, special, or consequential damages arising from your use of
            the App, including but not limited to damages from reliance on AI-generated recipes.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">10. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account at any time for violation
            of these Terms. You may delete your account at any time by contacting us.
            Upon termination, your right to use the App ceases immediately.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">11. Changes to Terms</h2>
          <p>
            We may update these Terms at any time. We will notify you of significant changes
            by updating the "Last updated" date. Continued use of the App after changes
            constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">12. Contact</h2>
          <p>For questions about these Terms, contact us at:</p>
          <p className="font-medium">support@quickchef.app</p>
        </section>

      </div>
    </div>
  );
}
